### ISSUE TITLE
Triage STF Tests

### ISSUE THREAD

**Issue by stp59** [cornell-netlab/petr4#109]
Could we get a list of needed externs from the v1model going in this issue? Thanks!

**Comment by hackedy** [comment]
Here are the tests failing due to missing externs as of d8eddd2. A lot of other tests probably rely on the same externs but are currently failing for other more boring reasons.

`register`
- examples/checker_tests/good/issue1097-2-bmv2.p4
- examples/checker_tests/good/issue1814-1-bmv2.p4 (also has an STF parser crash)

`update_checksum`
- examples/checker_tests/good/checksum3-bmv2.p4

`verify_checksum`
- examples/checker_tests/good/issue655-bmv2.p4
- examples/checker_tests/good/checksum1-bmv2.p4

`counter`
- examples/checker_tests/good/issue1566-bmv2.p4

`mark_to_drop`
- examples/checker_tests/good/issue1768-bmv2.p4

`hash`
- examples/checker_tests/good/constant-in-calculation-bmv2.p4
- examples/checker_tests/good/issue1049-bmv2.p4

**Comment by hackedy** [comment]
I haven't figured out what's going on with these STF tests, if anyone wants to try debugging them.
- [ ] examples/checker_tests/good/test-parserinvalidargument-error-bmv2.p4
- [ ] examples/checker_tests/good/subparser-with-header-stack-bmv2.p4
- [ ] examples/checker_tests/good/arith5-bmv2.p4
- [ ] examples/checker_tests/good/header-stack-ops-bmv2.p4
- [ ] examples/checker_tests/good/issue995-bmv2.p4
