### ISSUE TITLE
Non-decimal integer constants lexed incorrectly

### ISSUE THREAD

**Issue by liujed** [cornell-netlab/petr4#54]
The following program
```
const bit<16> IPV4x = 0x0;
const bit<16> IPV4d = 0d0;
const bit<16> IPV4o = 0o0;
const bit<16> IPV4b = 0b0;
const bit<16> IPV4 = 0;
```
is being parsed as
```
const bit<16> IPV4x = 720;
const bit<16> IPV4d = 520;
const bit<16> IPV4o = 630;
const bit<16> IPV4b = 500;
const bit<16> IPV4 = 0;
```
Root cause appears to be the invocation of `Bigint.of_string` by the lexer here: https://github.com/cornell-netlab/petr4/blob/981e36f10ee91ac84c23a8a4f5ad04029fdf9cd2/lib/lexer.mll#L78 which is called from https://github.com/cornell-netlab/petr4/blob/981e36f10ee91ac84c23a8a4f5ad04029fdf9cd2/lib/lexer.mll#L126-L133

**Comment by liujed** [comment]
This is with Core 0.13.0.

**Comment by hackedy** [comment]
Hi, thanks for the bug report. I took a look and our Bigint library only works with base 10, so I think the easiest fix for this is probably replacing the Bigint library with one that handles other bases.

**Comment by alexchang8** [comment]
I added the ocaml implementation of biginteger so that we could compile with js_of_ocaml, the issue being that zarith called external functions.

It looks like Jane Street has javascript stubs for zarith now we could try moving to that so that we could just use the normal bigint library and avoid any other problems.
https://github.com/janestreet/zarith_stubs_js
